### ISSUE TITLE
Websocket java.nio.channels.ClosedChannelException: null

### ISSUE THREAD

**Issue by bifunctor** [perwendel/spark#1101]
Hi all 
Disconnecting a client from the websocket, it throws the following exception: 

```
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:502)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.shutdownInput(AbstractEndPoint.java:107)
	at org.eclipse.jetty.io.ChannelEndPoint.fill(ChannelEndPoint.java:241)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:543)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

You can find the example on https://github.com/bifunctor/sparksocket. 

I tested the websocket with 

![Screenshot from 2019-03-16 21-59-37](https://user-images.githubusercontent.com/34632165/54481580-e3469b80-4836-11e9-8353-ecfcca67c9be.png)

Thanks

**Comment by lucastex** [comment]
Any news on this issue?

**Comment by lucastex** [comment]
Any news on this issue? Do this impact the server in any way?

**Comment by Lloyd-Pottiger** [comment]
I would like to work on this issue.

**Comment by Lloyd-Pottiger** [comment]
I have try using this example [spark-websocket](https://github.com/tipsy/spark-websocket) to reproduce the error, but can not make it. And the example url provided can not open anymore, I think it may not be a bug.
