### ISSUE TITLE
NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by floriancastelain** [perwendel/spark#1159]
**Version** : 2.9.1

**Stack trace**

> Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
> 	at spark.Service.<clinit>(Service.java:56)
> 	at spark.Spark$SingletonHolder.<clinit>(Spark.java:51)
> 	at spark.Spark.getInstance(Spark.java:55)
> 	at spark.Spark.<clinit>(Spark.java:61)
> 	at Api.<init>(Api.java:5)
> 	at generator.main(generator.java:61)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 6 more

**Steps to reproduce**

1. Download the jar from [here](https://repo1.maven.org/maven2/com/sparkjava/spark-core/) (2.9.1)
2. Create a simple class with a simple get:
import static spark.Spark.*;
```
public class Api {
	public Api() {
		get("test", (req, res) -> "hello, world");
	}
}
```
3. Use the api:
```
	public static void main(String[] args) throws InterruptedException {
		
		Api api = new Api();
```

------------------------

I had to the build path slf4j-simple-1.7.30, still the same problem.

Overview of the config:

![image](https://user-images.githubusercontent.com/10050024/72146879-ac311000-339d-11ea-8eab-1b665bbebc35.png)

**Comment by jbuisine** [comment]
Hello,

I had same issue and I added this `slf4j-simple` dependency version with `spark-core` 2.9.1:
```xml
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.21</version>
</dependency>
```

Now it seems to work well.

I just followed [Spark logger](http://sparkjava.com/documentation#examples-and-faq) documentation.

Hope it will help you !

**Comment by viniciusgati** [comment]
why is this a dependency that is not contained? i think the docs should mention it... and just to uipdate add the sl4j dependency only is not solving the problema
