### ISSUE TITLE
Error while running spark java application

### ISSUE THREAD

**Issue by chaurasiagautam** [perwendel/spark#1216]
`<spark.version>2.9.3</spark.version>`

Error:
Exception in thread "Thread-0" java.lang.NoSuchMethodError: 'javax.servlet.SessionCookieConfig spark.embeddedserver.jetty.JettyHandler.getSessionCookieConfig()'
	at spark.embeddedserver.jetty.EmbeddedJettyFactory.create(EmbeddedJettyFactory.java:52)
	at spark.embeddedserver.EmbeddedServers.create(EmbeddedServers.java:80)
	at spark.Service.lambda$init$2(Service.java:624)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by uraimo** [comment]
You likely have an obsolete jetty-server declared somewhere, updating to latest (9.x is ok too) fixed it for me.
