### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: spark/Route

### ISSUE THREAD

**Issue by heav-4** [perwendel/spark#1268]
i'm trying to run old software (2015ish) that is made using spark. 
```
  Exception in thread "main" java.lang.NoClassDefFoundError: spark/Route
	  at java.base/java.lang.Class.forName0(Native Method)
	  at java.base/java.lang.Class.forName(Class.java:488)
	  at java.base/java.lang.Class.forName(Class.java:467)
	  at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
  Caused by: java.lang.ClassNotFoundException: spark.Route
	  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	  ... 4 more
```

**Comment by lepe** [comment]
My guess is that your class path or the way you are compiling your project is mistaken. The class `spark.Route` should exists (just check in your dependencies or external libraries).
