### ISSUE TITLE
Session Invalidation Error

### ISSUE THREAD

**Issue by melvinma** [perwendel/spark#251]
Session invalidate and then recreated failed for me - The reason is, after invalidate a session, the session and the invalid HttpSession was not cleared out. I recommend the following code change in spark: in Request class, whenever access session variable, check if session is valid, if not valid, create a new session variable.

---- code having issues ----
			Session session = request.session(false);
			if (session!= null) session.invalidate();			
			session = request.session(true);
			session.attribute(SessionKeys.USER_ACCESS_TOKEN, "1234567");

---- exception I got ----

java.lang.IllegalStateException: null
	at org.eclipse.jetty.server.session.AbstractSession.checkValid(AbstractSession.java:104) ~[jetty-server-9.0.2.v20130417.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:79) ~[jetty-server-9.0.2.v20130417.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.AbstractSession.changeAttribute(AbstractSession.java:509) ~[jetty-server-9.0.2.v20130417.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.AbstractSession.setAttribute(AbstractSession.java:461) ~[jetty-server-9.0.2.v20130417.jar:9.2.7.v20150116]
	at spark.Session.attribute(Session.java:55) ~[spark-core-2.1.jar:na]

**Comment by perwendel** [comment]
Sorry for not looking at this earlier. I'm not the author of the session functionality so this might be a stupid question. If the underlying session is invalidated, shouldn't attribute() throw IllegalStateException?

**Comment by perwendel** [comment]
I looked a bit more. I guess it should be possible to create a new session after the old has been invalidated?

**Comment by jazdw** [comment]
There is no way to create a new session after the previous session has been invalidated. I had to work around this by using the underlying "raw" session. We need to be able to do this in order to change the session ID when logging in.

**Comment by jazdw** [comment]
Have a look at the Jetty Request.getSession(boolean) method. It checks if the session is valid and creates a new one if not.

**Comment by tipsy** [comment]
Fixed in 2.5
