### ISSUE TITLE
unable to run example code

### ISSUE THREAD

**Issue by kmulvey** [perwendel/spark#259]
The below occurs after pasting the example code and maven dependency into a project that already uses Apache Spark. Running this in its own project works fine, could there be name collision among the jars?

```
Exception in thread "Thread-0" java.lang.SecurityException: class "javax.servlet.SessionTrackingMode"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at spark.webserver.SparkServerFactory.create(SparkServerFactory.java:32)
	at spark.SparkBase$3.run(SparkBase.java:230)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by kmulvey** [comment]
turns out hadoop client was the culprit, removing that fixed it. Luckily  i dont need it but in case someone else runs into the same problem here is that dep:

```
		<dependency>
			<groupId>org.apache.hadoop</groupId>
			<artifactId>hadoop-client</artifactId>
			<version>2.6.0</version>
		</dependency>
```

**Comment by jmartin82** [comment]
The same problem with this dependency:

        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>2.7.0</version>
        </dependency>

Thanks for advice.
