### ISSUE TITLE
Uploading large files causes java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by JacoBriers** [perwendel/spark#284]
When uploading a large file and requesting the ServletInputStream from the raw HttpServletRequest:  

```
HttpServletRequest req = request.raw();  
stream = req.getInputStream();  
```

I get the following error: 

```
java.lang.OutOfMemoryError: Java heap space  
at java.util.Arrays.copyOf(Arrays.java:3236)   
at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)   
at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)  
at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)  
at spark.utils.IOUtils.toByteArray(IOUtils.java:134)  
at spark.webserver.JettyHandler$HttpRequestWrapper.cacheInputStream(JettyHandler.java:84)  
at spark.webserver.JettyHandler$HttpRequestWrapper.getInputStream(JettyHandler.java:78)  
```

Internally it looks like spark caches the input stream and causes the memory usage to spike. A solution could be to provide access to the raw uncached input stream with some utility function?  

```
HttpServletRequest req = request.raw();  
stream = req.getUncachedInputStream();  
```

I could raise the amount of heap space, but that would lead to high memory usage and not solve the underlying problem.

**Comment by Nbooo** [comment]
Got same issue now, just wondering if there is any workaround? Can I somehow fix this? (raising heap space isn't an option, obviously). Thanks in advance!

**Comment by flarno11** [comment]
related to issue #518

**Comment by tipsy** [comment]
Not sure if fixed. Closing this because we need to clean up. @jaco Please create a new issue if this is still a problem.
