### ISSUE TITLE
Serve up audio files from spark?

### ISSUE THREAD

**Issue by tchoulihan** [perwendel/spark#300]
So I'm serving up an mp3 from spark using:
```java
HttpServletResponse raw = res.raw();
raw.getOutputStream().write(Files.readAllBytes(Paths.get(path)));
raw.getOutputStream().flush();
raw.getOutputStream().close();
return res.raw();
```

But when scrolling to halfway through the song with my browser's player, it gives an exception:
```
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:186)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:335)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:125)
	at org.eclipse.jetty.server.HttpConnection.blockingWrite(HttpConnection.java:440)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:385)
	at org.eclipse.jetty.server.HttpChannel.commitResponse(HttpChannel.java:608)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:652)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
	at java.io.OutputStream.write(OutputStream.java:75)
```
```
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:165)
```

Has anyone been able to serve up audio files correctly?

**Comment by tchoulihan** [comment]
I just tried also serving up .mp3s using externalStaticFileLocation(), and they also are not seekable.

**Comment by pwittchen** [comment]
I have no experience in streaming mp3s yet, but I did small research a minute ago.
You can take a look at this solution: http://stackoverflow.com/questions/14410344/jersey-rest-support-resume-media-streaming/14476402#14476402 and try to implement something similar with Spark.
It requires some additional work, but it can be good starting point for a new feature.

**Comment by tchoulihan** [comment]
I actually have some code written for this working now, to do seekable streaming audio to various different mobile and desktop browsers. The above solution to do media streaming is not easy/trivial, and I think most people just give up and let apache do it instead of spark.

If you guys' like me to submit a pull request, I could do this. 

I could provide it with a method like:

```java
public static Response streamAudioFile(File audioFile)
```

If you'd like, you can add this as a feature request, and let me know.

**Comment by tipsy** [comment]
Created a feature request, #397. How many lines of code are we talking?
