### ISSUE TITLE
IllegalArgumentException when using unsupported HTTP methods

### ISSUE THREAD

**Issue by zeroflag** [perwendel/spark#346]
Hi,

This came out during a security analysis. Using an unsupported HTTP method causes IllegalArgumentException in MatcherFilter.java:130. 

It would be more appropriate to raise a "405 Method not allowed", "404 Not found" or something other then "500 Internal Server Error".

E.g.: 
 GET /foo/bar            -> Ok
 CUSTOM /foo/bar    -> error
 LOCK /foo/bar          -> error
 COPY /foo/bar          -> error
 etc

Stacktrace:

java.lang.IllegalArgumentException: No enum constant spark.route.HttpMethod.lock
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_51]
	at spark.route.HttpMethod.valueOf(HttpMethod.java:22) ~[spark-core-2.2.jar:na]
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:130) ~[spark-core-2.2.jar:na]
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60) [spark-core-2.2.jar:na]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.Server.handle(Server.java:451) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266) [jetty-server-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240) [jetty-io-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [jetty-util-9.0.2.v20130417.jar:9.0.2.v20130417]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [jetty-util-9.0.2.v20130417.jar:9.0.2.v20130417]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by zeroflag** [comment]
Interestingly I can't reproduce this in the GenericIntegrationTest, because jetty rejects the request before the sparkfilter could process it. But if I create a standalone spark application the problem comes.
