### ISSUE TITLE
Stop/restart Jetty after running HelloWorld

### ISSUE THREAD

**Issue by belgoros** [perwendel/spark#39]
I didn't find any tips or answers on how to stop/restart Jetty instance after running the simple HelloWorld class. Once started, no way to rerun the same class. I just took the supplied HelloWorld example and tried to re-run it after some modification. here is what I got in Eclipse console:

```
log4j:WARN No appenders could be found for logger (spark.route.RouteMatcherFactory).
log4j:WARN Please initialize the log4j system properly.
== Spark has ignited ...
>> Listening on 0.0.0.0:4567
java.net.BindException: Address already in use: JVM_Bind
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:365)
    at java.net.ServerSocket.bind(ServerSocket.java:319)
    at java.net.ServerSocket.<init>(ServerSocket.java:185)
    at java.net.ServerSocket.<init>(ServerSocket.java:141)
    at org.eclipse.jetty.server.bio.SocketConnector.newServerSocket(SocketConnector.java:86)
    at org.eclipse.jetty.server.bio.SocketConnector.open(SocketConnector.java:75)
    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:356)
    at org.eclipse.jetty.server.bio.SocketConnector.doStart(SocketConnector.java:146)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at org.eclipse.jetty.server.Server.doStart(Server.java:269)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
    at spark.webserver.SparkServerImpl.ignite(SparkServerImpl.java:64)
    at spark.Spark$1.run(Spark.java:197)
    at java.lang.Thread.run(Thread.java:619)
```

There is no service running in Windows services list either. Any idea? Thanks

**Comment by bliti** [comment]
Just dropping this here:

I'm enjoying Spark with Netbeans and was facing a similar issue. I was able to find and modify a bash script that worked (under Linux and OSX, not Windows support).

I've put it up in github:

https://github.com/bliti/killnetty

**Comment by choidamdam** [comment]
For eclipse users, this might be helpful: 
http://www.codeaffine.com/2016/04/19/terminate-relaunch-eclipse/

**Comment by var23rav** [comment]
Use command for this.

**Windows**
get process id using
_netstat -a -o -n | findstr port_num_
kill process
_taskkill /F /PID process_id_

**Ubuntu**
_fuser -k port_num/tcp_
