### ISSUE TITLE
javax/servlet/Filter ClassNotFound when Spark.get

### ISSUE THREAD

**Issue by vishal-biyani** [perwendel/spark#45]
I am using 
<code>
      Spark.get(new Route("/")
</code>
Which calls 
<code>
      server = SparkServerFactory.create();
</code>

And I am getting exception

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: javax/servlet/Filter
    at spark.Spark$1.run(Spark.java:196)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 2 more

**Comment by phase** [comment]
@vishal-biyani Having these same problem, where did you find a download?

**Comment by vishal-biyani** [comment]
@phase been long but as long as I can recall - I did not add dependency manually - but added in Maven.  From the Git page, latest one looks like:
   <dependency>
        <groupId>com.sparkjava</groupId>
        <artifactId>spark-core</artifactId>
        <version>2.2</version>
    </dependency>
