### ISSUE TITLE
SparkApplication throws exception when threadpool size is specified.

### ISSUE THREAD

**Issue by debarshri** [perwendel/spark#457]
I am trying to use SparkApplication so that I can use spark in a war.

If I specify set the threadpool I get this exception

```
java.lang.IllegalStateException: This must be done before route mapping has begun   at spark.servlet.SparkFilter.init(SparkFilter.java:71)  at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:271)    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)     at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4828)  at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5508)    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)     at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1862)    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)  at java.lang.Thread.run(Thread.java:745)
```

However, If I use the embedded server I with the threadpool size, I do not get this error.

It is how it is meant to behave?

**Comment by tipsy** [comment]
I think that method is only for the embedded server, yes.

**Comment by debarshri** [comment]
Wouldn't it be nice, if we don't get IllegalState instead those parameters are ignored.
