### ISSUE TITLE
jetty-server-*.jar required even when running on Tomcat

### ISSUE THREAD

**Issue by kliakos** [perwendel/spark#461]
I used to exclude the jetty-server-*.jar for my Tomcat war build.

Latest version of Spark however has a problem with this, and throws ClassNotFoundException.

`Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
        at spark.embeddedserver.EmbeddedServers.<clinit>(EmbeddedServers.java:37
)
        at spark.SparkInstance.<init>(SparkInstance.java:71)
        at spark.Spark$SingletonHolder.<clinit>(Spark.java:44)
        at spark.Spark.getInstance(Spark.java:48)
        at spark.Spark.get(Spark.java:564)
        ... 58 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClas
sLoaderBase.java:1305)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClas
sLoaderBase.java:1157)
        ... 63 more`

**Comment by perwendel** [comment]
Fixed!
