### ISSUE TITLE
Using spark-core:2.3 simple Groovy Hello World fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by kohanyirobert** [perwendel/spark#523]
I've wanted to try out Spark using Groovy with the following code example.
```
// hello.groovy
@Grab('com.sparkjava:spark-core:2.3') // or 2.2
import static spark.Spark.*;

get '/hello', {req, res -> 'Hello World'}
```

Just execute it like `groovy hello.groovy`.

When I access `http://localhost:4567/hello` the following internal error happens.

```
[qtp1240941773-19] WARN org.eclipse.jetty.server.HttpChannel - //localhost:4567/hello
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeaders(Ljava/lang/String;)Ljava/util/Collection;
        at spark.utils.GzipUtils.checkAndWrap(GzipUtils.java:64)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:251)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
```

The same thing works when using `spark-core:2.0.0` ~(I was not able to try `2.1`, because the dependencies failed to download)~. `spark-core:2.1` works also.

I'm not sure what's the issue, but if this works with `spark-core:2.{0.0,1}` then I assume it should work with `2.2` and `2.3` as well.

**Comment by t-kameyama** [comment]
The servlet-api of groovy's lib is used.

```
// hello.groovy
@Grab('com.sparkjava:spark-core:2.3')
import static spark.Spark.*;
get '/hello', {req, res -> 'Hello World'}

println(getClass().classLoader.getResource('javax/servlet/http/HttpServletResponse.class')) 
// -> jar:file:/YOUR_GROOVY_DIR/lib/servlet-api-2.4.jar!/javax/servlet/http/HttpServletResponse.class
```

I think that it's Grape or Groovy problems.

Please try to use the Gradle.
```
// src/main/groovy/hello.groovy
import static spark.Spark.*;
get '/hello', {req, res -> 'Hello World'}
```

```
// build.gradle
apply plugin: 'groovy'

task runScript (dependsOn: 'classes', type: JavaExec) {
	main = 'hello'
	classpath = sourceSets.main.runtimeClasspath
}

dependencies {
	compile 'org.codehaus.groovy:groovy-all:2.4.4'
	compile 'com.sparkjava:spark-core:2.3'
}

repositories {
    mavenCentral()
}
```

```
$ gradle runScript
```

**Comment by kohanyirobert** [comment]
Hmm, did a bit of digging, it seems like a [known issue for quite some time](https://issues.apache.org/jira/browse/GROOVY-5727). Commented on the ticket in the Groovy JIRA, maybe somebody will pick it up. I can confirm that Gradle works as expected.

**Comment by at88mph** [comment]
Is there a workaround for this?  I tried:

`
...
compile ('com.sparkjava:spark-core:2.3') {
    exclude module: 'servlet-api'
}
...
`

To try and install the 3.1 `servlet-api`, but I may be doing the exclude incorrectly.

Thanks.

**Comment by paulk-asert** [comment]
Groovy master branch (targeted for a currently unscheduled upcoming 2.5 release) is now using javax.servlet-api:3.0.1. The original script now works for me in master.

**Comment by RobertRacklBMW** [comment]
Is there a workaround? How do I force my groovy installation to use the "master branch"? Can I install this as some kind of beta?

Or would it already help to replace the javax.servlet JAR file under groovy/lib ?
