### ISSUE TITLE
Jar running issues

### ISSUE THREAD

**Issue by rucuriousyet** [perwendel/spark#556]
I just ran the spark helloworld tutorial without issue, but when I try to export the program as a jar in intellij (using artifacts) I get the following error:

```
/usr/lib/jvm/java-8-oracle/bin/java -Dfile.encoding=UTF-8 -jar /home/digitalblueeye/IdeaProjects/SparkREST/out/artifacts/unnamed/unnamed.jar
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: spark/Request
    at Main.main(Main.java:8)
Caused by: java.lang.NoClassDefFoundError: spark/Request
    ... 1 more
Caused by: java.lang.ClassNotFoundException: spark.Request
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

Process finished with exit code 1
```

**Comment by vandershraaf** [comment]
Based on the command you ran, it seems that you didn't include the Spark jar file in classpath as dependency. You will probably need to either add the Spark jar in the Classpath (i.e CLASSPATH=path/to/jar), or include it when building your program jar.
