### ISSUE TITLE
NullPointerException RouteOverview.enableRouteOverview() 

### ISSUE THREAD

**Issue by luanrmuller** [perwendel/spark#583]
Good evening, I have a problem when adding a uri that uses a ResponseTransformer when Spark creates a new ResponseTransformerRouteImpl the constructor is not sending the Route to initialize the variable 'delegate' in RouteImpl class causing an NullPointerException when I call  "/my/overview/path " of RouteOverview.enableRouteOverview

My code:
```java
RouteOverview.enableRouteOverview();
          Spark.get("/teste", "application/json", (request, response) -> {
		 return "teste";
	 } , new JsonTransformer();
```

Routable::593
```java
public void post(String path, String acceptType, Route route, ResponseTransformer transformer) {
        addRoute(HttpMethod.post.name(), ResponseTransformerRouteImpl.create(path, acceptType, route, transformer));
    }
```

ResponseTransformerRouteImpl::53
```java
protected ResponseTransformerRouteImpl(String path, String acceptType) {
        super(path, acceptType);
    }
```

When calling the super 'super (patch, acceptType);' send the Route ->  'super (patch, acceptType, route);' ?

`java.lang.NullPointerException
	at spark.route.RouteOverview.createHtmlForRouteTarget(RouteOverview.java:87)
	at spark.route.RouteOverview.lambda$createHtmlOverview$2(RouteOverview.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at spark.route.RouteOverview.createHtmlOverview(RouteOverview.java:79)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by AzureusNation** [comment]
@luanrmuller When I try and recreate this I jut get an 500 error from the server and no stack trace. This might be me being stupid. Can you share your exact code please.

Also when sharing code place it with three ` and java straight after for syntax highlighting. Makes it a lot easier to read.

**Comment by tipsy** [comment]
> When I try and recreate this I jut get an 500 error from the server and no stack trace

Add `exception(Exception.class, (e, req, res) -> e.printStackTrace());`.
Spark doesn't print exceptions by default.

**Comment by AzureusNation** [comment]
Ok I've found the issue.

When the route is added at start up it goes through to the RouteOverview class and the method add gets run. Now during that method is when the null happens. The wrapped object being passed through is an instance of a ResponceTransformerRouteImpl which extends RouteImpl and that includes Wrapper.

The problem being is the ResponceTransformerRouteImpl is never given a delegate in the RouteImpl and therefore when the method is run and it tries to get the delegate it returns null.

A quick fix ive found is this:
```java
if (wrapped instanceof Wrapper && !(wrapped instanceof ResponseTransformerRouteImpl)) {
            entry.target = ((Wrapper) wrapped).delegate();
        }
```

But that's more hacky than a fix. I'm going to see how the delegate gets added and see if there is a better way to fix this issue.

**Comment by AzureusNation** [comment]
So I found the route cause of the error. Turns out that when a ResponceTransformerRouteImpl is instantiated the route that is passed to it never gets passed to the super method in RouteImpl, and there for delegate is null. I have rectified this and a PR will be on its way very shortly.
