### ISSUE TITLE
NullPointerException when reading static files in a jar

### ISSUE THREAD

**Issue by DOFandersolsen** [perwendel/spark#745]
Hello,

I have an issue which is probably closely related to https://github.com/perwendel/spark/issues/535

Inside my application, I setup the following before setting the routes:
`staticFileLocation("/public");`

Under my resources folder in my project, I have the following structure (Names has been changed to not leak data about the project)
```
├── public
│   └── API
│       └── v1
│           └── doc
│                 └── index.html
```

Inside my controller, I have registred the following redirects:
```
/API/v1/ -> /API/v1/doc/
/API/v1/doc -> /API/v1/doc/
```

This means that if you write /API/v1/doc, you are redirected to /API/v1/doc/ which serves index.html inside the folder. So far so good!

Now, when I compile everything into a shaded jar using `maven-compiler-plugin` and `maven-shade-plugin` suddenly, I get `NullPointerException` problems when trying to use my redirect.

I have traced it down to the following:
```
java.lang.NullPointerException
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at spark.utils.IOUtils.copyLarge(IOUtils.java:186)
	at spark.utils.IOUtils.copy(IOUtils.java:159)
	at spark.staticfiles.StaticFilesConfiguration.consumeWithFileResourceHandlers(StaticFilesConfiguration.java:97)
	at spark.staticfiles.StaticFilesConfiguration.consume(StaticFilesConfiguration.java:69)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:93)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

Using `java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -jar target/API.jar` and remote debugging in IntelliJ IDEA, I see the problem inside `StaticFilesConfiguration.java:89`

When serving through the IDE, the `resource.isReadable()` function resolves the URL as `file:/Users/Anders/workspace/API/spark/target/classes/public/API/v1/doc`

For this URL, `ResourceUtils.isFileURL(url)` returns true and a new `File` object is created.
Spark now calls `file.canRead() && !file.isDirectory()` which returns false since it's a directory and not a content-filled file.

When serving through the JAR the `resource.isReadable()` function resolves the URL as `jar:file:/Users/Anders/workspace/API/spark/target/API.jar!/public/API/v1/doc`.

On `AbstractFileResolvingResource.java:109` the call to `isFileURL(url)` returns `false` and then we jump directly to `AbstractFileResolvingResource.java:114` and returns `true` for `isReadable()`

Going back to `StaticFilesConfiguration.java:89` we suddenly enter the if-loop, despite our URL not being a File and no reading check has been done. 

When we reach `StaticFilesConfiguration.java:97` we try to copy the content with `                    IOUtils.copy(resource.getInputStream(), wrappedOutputStream);` which causes a NullPointerException somewhere deep inside.

I think the problem lies in `AbstractFileResolvingResource.java:114` where Spark needs to do a try-catch, see if it can open the resource and if not, return false, so the mapped routes can handle the problem.

**Comment by jwassil** [comment]
I'm still seeing this issue in v2.6.0.  I'm compiling to a JAR, with my static files in `public/`.  When I try to get `http://<host>:<port>/firstDirectory`, I get this exception, but getting `http://<host>:<port>/firstDirectory/` works fine.

**Comment by vlightyear** [comment]
I have a similar problem. Executing this with Intellij works fine.
But when the site is served from a compiled jar the follow stack trace shows.

[qtp1366863974-24] WARN org.eclipse.jetty.server.HttpChannel - //********** (This is the URL)
java.lang.NullPointerException
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at spark.utils.IOUtils.copyLarge(IOUtils.java:186)
        at spark.utils.IOUtils.copy(IOUtils.java:159)
        at spark.staticfiles.StaticFilesConfiguration.consumeWithFileResourceHandlers(StaticFilesConfiguration.java:97)
        at spark.staticfiles.StaticFilesConfiguration.consume(StaticFilesConfiguration.java:69)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:94)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)

Someone please help.

**Comment by albarra** [comment]
Same issue with version 2.8
