### ISSUE TITLE
OutOfMemoryError cause while uploading large file

### ISSUE THREAD

**Issue by zhangqianliang** [perwendel/spark#876]
spark version: 2.6.0
When uploading a large file and requesting the ServletInputStream from the raw HttpServletRequest:
```
            Part part = request.raw().getPart("file");
            try (InputStream is = part.getInputStream()) {
                Files.copy(is, tempFile, StandardCopyOption.REPLACE_EXISTING);
            }
```
I get the following error:
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:135)
	at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:138)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:748)
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:441)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2337)
	at org.eclipse.jetty.server.Request.getParts(Request.java:2316)
	at org.eclipse.jetty.server.Request.getPart(Request.java:2305)
	at javax.servlet.http.HttpServletRequestWrapper.getPart(HttpServletRequestWrapper.java:386)
```

**Comment by s4mpl3d** [comment]
What's the partsize?

**Comment by weickmanna** [comment]
Root cause of this might be #876

**Comment by mrieser** [comment]
Looks like a duplicate of #889.

**Comment by weickmanna** [comment]
Ah yes, that's what I meant actually :-)
