### ISSUE TITLE
OutOfMemoryError when uploading many / large files

### ISSUE THREAD

**Issue by weickmanna** [perwendel/spark#889]
Running into this problem that others also reported via StackOverflow already:
https://stackoverflow.com/questions/36431697/large-file-upload-with-spark-framework

The problem is that Spark will always load the entire request as bytes into memory, which makes large file uploads basically impossible.

I might need to upload up to ~ 100 image files where each image file might have ~ 10 mb.

```
 java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236) ~[?:1.8.0_91]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118) ~[?:1.8.0_91]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[?:1.8.0_91]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153) ~[?:1.8.0_91]
	at spark.utils.IOUtils.toByteArray(IOUtils.java:134) ~[spark-core-2.6.0.jar:?]
	at spark.embeddedserver.jetty.HttpRequestWrapper.cacheInputStream(HttpRequestWrapper.java:62) ~[spark-core-2.6.0.jar:?]
	at spark.embeddedserver.jetty.HttpRequestWrapper.getInputStream(HttpRequestWrapper.java:56) ~[spark-core-2.6.0.jar:?]
	at org.apache.commons.fileupload.servlet.ServletRequestContext.getInputStream(ServletRequestContext.java:112) ~[commons-fileupload-1.3.3.jar:1.3.3]
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:952) ~[commons-fileupload-1.3.3.jar:1.3.3]
	at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:310) ~[commons-fileupload-1.3.3.jar:1.3.3]
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:334) ~[commons-fileupload-1.3.3.jar:1.3.3]
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:115) ~[commons-fileupload-1.3.3.jar:1.3.3]
```

**Comment by jakaarl** [comment]
Resolved by #891 ?
