### ISSUE TITLE
Static files not serving from inside a compiled JAR

### ISSUE THREAD

**Issue by glorantq** [perwendel/spark#917]
The title says it all - static files aren't serving from inside a compiled JAR. They work just fine from within IntelliJ.

I set the location like this:
`http.staticFiles.location("/htdocs/public/")`

And ran from IntelliJ everything works fine:
![image](https://user-images.githubusercontent.com/17655680/30563687-e91e995c-9cc2-11e7-8470-3de792ec8159.png)

But ran from the compiled JAR it's rather disappointing:
![image](https://user-images.githubusercontent.com/17655680/30563668-dc0bafa2-9cc2-11e7-947d-680e32d0c0fa.png)

Am I missing something here? I can't seem to find a way to specify a ClassLoader, so what can be the solution here? The files are clearly packaged inside the archive:
![image](https://user-images.githubusercontent.com/17655680/30563773-36535154-9cc3-11e7-9f92-c558f997a327.png)

**Comment by glorantq** [comment]
Clarification: Template files are loaded correctly from the same htdocs folder because they have the ClassLoader set.

**Comment by alexkarpandrus** [comment]
@glorantq I've faced the same issue. Workaround that worked for me was to use `externalLocation` method instead and hold my static files outside of jar. 
Nevertheless, that's a bug.

**Comment by glorantq** [comment]
That's what I've been doing, however it's really annoying in production, as I have to copy that folder on the server as well. Would be good if could just get a

setClassLoader
``` method like with the Freemarker engine

**Comment by ijabz** [comment]
So I think this is a bug because if we look at InlineStaticResource you can see  that even if we retrieve the file as a resource (i.e from a jar) we then try to load it as a file in the readasFile method, but its not a file its a stream !

 ```
public static String getFileAsString(String path) {
        try {
            return readFileAsString(InlineStaticResource.class.getResource(path).getPath());
        } catch (Exception var4) {
            try {
                return readFileAsString(path);
            } catch (Exception var3) {
                throw new RuntimeException("Couldn't find file with path='" + path + "'");
            }
        }
    }

    private static String readFileAsString(String path) throws IOException {
        BufferedReader bufferedReader = new BufferedReader(new FileReader(path));
        StringBuilder sb = new StringBuilder();

        int c;
        while((c = bufferedReader.read()) >= 0 && c >= 0) {
            sb.append((char)c);
        }

        return sb.toString();
    }
```

I added the folowing to my code to demonstrate this
 try
        {
            System.out.println("*************"+InlineStaticResource.class.getResource("/artwork.js").toString());
            System.out.println("*************"+InlineStaticResource.class.getResource("/artwork.js").getPath());
            System.out.println("*************"+new FileReader(InlineStaticResource.class.getResource("/artwork.js").getPath()));
        }
        catch(Exception e)
        {
            MainWindow.logger.log(Level.SEVERE, e.getMessage(), e);
        }

Giving output as follows

*************jar:file:/C:/Program%20Files/Jthink/SongKong/lib/songkong-5.2.jar!/artwork.js
*************file:/C:/Program%20Files/Jthink/SongKong/lib/songkong-5.2.jar!/artwork.js
Mar 14, 2018 3:00:39 PM com.jthink.songkong.cmdline.SongKong main
SEVERE: file:\C:\Program%20Files\Jthink\SongKong\lib\songkong-5.2.jar!\artwork.js (The filename, directory name, or volume label syntax is incorrect)
java.io.FileNotFoundException: file:\C:\Program%20Files\Jthink\SongKong\lib\songkong-5.2.jar!\artwork.js (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at com.jthink.songkong.cmdline.SongKong.main(SongKong.java:2412)

As you can see it finds the reosurce in the jar okay, the problem is when it trys to read it as a file, instead I think it should use InputStreamReader

**Comment by ijabz** [comment]
Actually its a bug in j2html not spark - https://github.com/tipsy/j2html/issues/108

**Comment by ijabz** [comment]
Sorry gettting confused between spark framework and j2html  but the problem in  j2html seems similar, and was fixed in 1.2.1
