### ISSUE TITLE
Newb question - not a good start

### ISSUE THREAD

**Issue by ORESoftware** [perwendel/spark#919]
I run the follow commands

```bash
mvn package # works fine, build successful
java -cp target/cdt-hive-1.0-SNAPSHOT.jar cdt.App  # causes error below
```

```bash
$ java -cp target/cdt-hive-1.0-SNAPSHOT.jar cdt.App
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: spark/Request
        at cdt.App.main(App.java:8)
Caused by: java.lang.NoClassDefFoundError: spark/Request
        ... 1 more
Caused by: java.lang.ClassNotFoundException: spark.Request
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

```

here is the code I used:

```java
package cdt;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
        get("/hello", (req, res) -> "Hello World");
    }
}
```

and my pom.xml file:

```xml
<project>

    <modelVersion>4.0.0</modelVersion>
    <groupId>cdt</groupId>
    <artifactId>cdt-hive</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>cdt-hive</name>
    <url>http://maven.apache.org</url>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.8.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.thrift</groupId>
            <artifactId>libthrift</artifactId>
            <version>0.10.0</version>
        </dependency>
        <dependency>
            <groupId>com.sparkjava</groupId>
            <artifactId>spark-core</artifactId>
            <version>2.5</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by jakaarl** [comment]
You're not packaging dependencies in the JAR.

I suggest using Maven assembly plugin's  `jar-with-dependencies`, see: https://maven.apache.org/plugins/maven-assembly-plugin/usage.html
Also, on the same page, see "Creating an Executable JAR". It's handy.

**Comment by ORESoftware** [comment]
ok thanks appreciated
