### ISSUE TITLE
kerberos authentication in spark 2.2.0

### ISSUE THREAD

**Issue by adoniswu** [perwendel/spark#972]
version of spark: 2.2.0
the method to commit spark task is: new SparkLauncher();
we get exception like：
Exception in thread "main" org.apache.spark.SparkException: Unable to load YARN support
	at org.apache.spark.deploy.SparkHadoopUtil$.liftedTree1$1(SparkHadoopUtil.scala:405)
Caused by: java.lang.IllegalArgumentException: Can't get Kerberos realm
Caused by: KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1006)
	... 31 more
Caused by: KrbException: Generic error (description in e-text) (60) - Unable to locate Kerberos realm
	at sun.security.krb5.Config.getRealmFromDNS(Config.java:1102)

**Comment by FireArrow** [comment]
This is the web framework Spark, not to be confused with Apache Spark (https://spark.apache.org/). You have problem with Apache Spark. (You seem to be missing /etc/krb.conf,  but I'm not sure, and I can't help you further here).
